[package]
name = "root"
version = "0.1.0"
edition = "2021"


[dependencies]
async-trait = "0.1.74"
futures = "0.3.29"
futures-util = "0.3.29"
reqwest = { version = "0.11.22", features = ["stream"] }
tokio = { version = "1.34.0", features = ["full"] }
