name: check-init
run-name: ${{ github.actor }} npm install i -g nsv 🚀
on:
    push:
        branches:
            - main
jobs:
    system:
        runs-on: [windows-latest]
        # runs-on: [macos-latest]
        env:
            DEBUG: true
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: main
            -   run: npm install
                continue-on-error: true
            -   run: npm run build
            -   run: npm run init
            -   run: ./nsv use 14.17.1
            -   run: where.exe node
            -   run: "Get-ChildItem Env:"
            -   run: node -v
            -   run: |
                    result=$(echo "$OUTPUT" | grep "v14.17.1")
                    if [ -z "$result" ]; then
                      echo "node version is not match"
                      exit 1
                    fi
                    echo "node version match ok"
                shell: bash
