name: check-init
run-name: ${{ github.actor }} npm install i -g nsv 🚀
on:
    push:
        branches:
            - test
jobs:
    windows:
        runs-on: [macos-latest]
        env:
            DEBUG: true
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: test
            -   run: npm install
            -   run: ./nsv use 16
